### PR TITLE
Improved APM calculation accuracy

### PR DESCRIPTION
**Pull request by tylerkerr**
The existing APM calculation is basically (actions / minutesPlayed) and minutesPlayed does not round at all, so if a game is 5m01s long, APM is calculated based on a game length of exactly 6 minutes. That causes minor inaccuracies which depend on the exact length of the game.

There's a larger inaccuracy, too - in a team game, if a player leaves but the game continues, the parser will continue adding 0s to the 'timed' list for each minute, so the leaver's APM is calculated not based on their ingame time but the total length of the replay.

It looks like currentTimePlayed is susceptible to inaccuracy via an AFKing player, but it seems like an acceptable compromise that the starting when a player begins AFKing through the end of the replay are not counted toward their calculated APM.

### CODE REVIEW

**Comment by PBug90** [comment]
Good catch again. The changed logic seems to be fine and fit the use case better. The only thing missing is a test with a team game and a leaving player. Can you add one?

**Comment by tylerkerr** [comment]
Replay and test case added, let me know how that looks.

**Comment by PBug90** [comment]
Two things regarding the test:

I would like to see an additional assertion on the _timed_ array so that you can see the zero values that indicate a leaving player in the test case. You could replace the time played * 0.7 assertion with that. 


```
expect(test.players[0].apm).toBeGreaterThan(80)
```
While this is fine to cover the changes made, a future change could be overseen if the apm value changes to a greater value. You could just fix this value to be exactly the apm value in the player so changes in apm calculation that result in a different exact value for this particular player fail the test.

**Comment by tylerkerr** [comment]
OK, updated/refined the assertions.

**Pull request merged**
